apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpl1
  template:
    metadata:
      labels:
        app: dpl1
    spec:
      containers:
      - name: dpl1
        image: pabloescales/kubectl-test:mi-imagen
        ports:
        - containerPort: 8091
---

apiVersion: v1
kind: Service
metadata:
  name: mi-aplicacion-service
spec:
  selector:
    app: dpl1
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: NodePort